<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace Template;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>template.DB</code>
 */
class DB extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes Items = 1;</code>
     */
    private $Items;
    /**
     * Generated from protobuf field <code>repeated bytes JobCategories = 2;</code>
     */
    private $JobCategories;
    /**
     * Generated from protobuf field <code>repeated bytes Masterpieces = 3;</code>
     */
    private $Masterpieces;
    /**
     * Generated from protobuf field <code>repeated bytes CraftLevelDifferences = 4;</code>
     */
    private $CraftLevelDifferences;
    /**
     * Generated from protobuf field <code>repeated bytes Currencies = 5;</code>
     */
    private $Currencies;
    /**
     * Generated from protobuf field <code>repeated bytes Books = 6;</code>
     */
    private $Books;
    /**
     * Generated from protobuf field <code>repeated bytes Areas = 7;</code>
     */
    private $Areas;
    /**
     * Generated from protobuf field <code>repeated bytes Aetherytes = 8;</code>
     */
    private $Aetherytes;
    /**
     * Generated from protobuf field <code>repeated bytes RouterPaths = 9;</code>
     */
    private $RouterPaths;
    /**
     * Generated from protobuf field <code>repeated bytes GatherSpots = 10;</code>
     */
    private $GatherSpots;
    /**
     * Generated from protobuf field <code>repeated bytes EphemeralSpots = 11;</code>
     */
    private $EphemeralSpots;
    /**
     * Generated from protobuf field <code>repeated bytes UnspoiledSpots = 12;</code>
     */
    private $UnspoiledSpots;
    /**
     * Generated from protobuf field <code>repeated bytes GrindSpots = 13;</code>
     */
    private $GrindSpots;
    /**
     * Generated from protobuf field <code>repeated bytes Recipes = 14;</code>
     */
    private $Recipes;
    /**
     * Generated from protobuf field <code>repeated bytes Npcs = 15;</code>
     */
    private $Npcs;
    /**
     * Generated from protobuf field <code>repeated bytes FishingEntries = 16;</code>
     */
    private $FishingEntries;
    /**
     * Generated from protobuf field <code>repeated bytes Shops = 17;</code>
     */
    private $Shops;
    /**
     * Generated from protobuf field <code>repeated bytes Reputations = 18;</code>
     */
    private $Reputations;
    /**
     * Generated from protobuf field <code>repeated bytes GatherSkills = 19;</code>
     */
    private $GatherSkills;
    /**
     * Generated from protobuf field <code>repeated bytes FishingSpots = 20;</code>
     */
    private $FishingSpots;
    /**
     * Generated from protobuf field <code>repeated bytes Leves = 21;</code>
     */
    private $Leves;
    /**
     * Generated from protobuf field <code>repeated .template.TranslationMaps TranslationMaps = 22;</code>
     */
    private $TranslationMaps;
    /**
     * Generated from protobuf field <code>repeated bytes Weather = 23;</code>
     */
    private $Weather;
    /**
     * Generated from protobuf field <code>repeated bytes LevelingBlocks = 24;</code>
     */
    private $LevelingBlocks;
    /**
     * Generated from protobuf field <code>repeated bytes Mounts = 25;</code>
     */
    private $Mounts;
    /**
     * Generated from protobuf field <code>repeated bytes FishingRecords = 26;</code>
     */
    private $FishingRecords;
    /**
     * Generated from protobuf field <code>repeated bytes DiademSearchpointCircuit = 27;</code>
     */
    private $DiademSearchpointCircuit;
    /**
     * Generated from protobuf field <code>repeated bytes ResourceApprovals = 28;</code>
     */
    private $ResourceApprovals;
    /**
     * Generated from protobuf field <code>bytes SummoningBellIds = 29;</code>
     */
    protected $SummoningBellIds = '';
    /**
     * Generated from protobuf field <code>repeated bytes RetainerNames = 30;</code>
     */
    private $RetainerNames;
    /**
     * Generated from protobuf field <code>repeated bytes DiademSpots = 31;</code>
     */
    private $DiademSpots;
    /**
     * Generated from protobuf field <code>repeated bytes Quests = 32;</code>
     */
    private $Quests;
    /**
     * Generated from protobuf field <code>repeated bytes CircuitSpots = 33;</code>
     */
    private $CircuitSpots;
    /**
     * Generated from protobuf field <code>repeated bytes SextantZoneHeaders = 34;</code>
     */
    private $SextantZoneHeaders;
    /**
     * Generated from protobuf field <code>repeated bytes Landpoints = 35;</code>
     */
    private $Landpoints;
    /**
     * Generated from protobuf field <code>repeated bytes Materia = 36;</code>
     */
    private $Materia;
    /**
     * Generated from protobuf field <code>repeated bytes Consumables = 37;</code>
     */
    private $Consumables;
    /**
     * Generated from protobuf field <code>repeated bytes ItemSeries = 38;</code>
     */
    private $ItemSeries;
    /**
     * Generated from protobuf field <code>repeated bytes DiademMobs = 39;</code>
     */
    private $DiademMobs;
    /**
     * Generated from protobuf field <code>bytes TreasureMaps = 40;</code>
     */
    protected $TreasureMaps = '';
    /**
     * Generated from protobuf field <code>bytes IshgardPoints = 41;</code>
     */
    protected $IshgardPoints = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Items
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $JobCategories
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Masterpieces
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $CraftLevelDifferences
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Currencies
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Books
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Areas
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Aetherytes
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $RouterPaths
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $GatherSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $EphemeralSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $UnspoiledSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $GrindSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Recipes
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Npcs
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $FishingEntries
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Shops
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Reputations
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $GatherSkills
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $FishingSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Leves
     *     @type \Template\TranslationMaps[]|\Google\Protobuf\Internal\RepeatedField $TranslationMaps
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Weather
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $LevelingBlocks
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Mounts
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $FishingRecords
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $DiademSearchpointCircuit
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ResourceApprovals
     *     @type string $SummoningBellIds
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $RetainerNames
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $DiademSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Quests
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $CircuitSpots
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $SextantZoneHeaders
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Landpoints
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Materia
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Consumables
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ItemSeries
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $DiademMobs
     *     @type string $TreasureMaps
     *     @type string $IshgardPoints
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes Items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Items = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes JobCategories = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJobCategories()
    {
        return $this->JobCategories;
    }

    /**
     * Generated from protobuf field <code>repeated bytes JobCategories = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJobCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->JobCategories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Masterpieces = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMasterpieces()
    {
        return $this->Masterpieces;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Masterpieces = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMasterpieces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Masterpieces = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes CraftLevelDifferences = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCraftLevelDifferences()
    {
        return $this->CraftLevelDifferences;
    }

    /**
     * Generated from protobuf field <code>repeated bytes CraftLevelDifferences = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCraftLevelDifferences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->CraftLevelDifferences = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Currencies = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCurrencies()
    {
        return $this->Currencies;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Currencies = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCurrencies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Currencies = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Books = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBooks()
    {
        return $this->Books;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Books = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBooks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Books = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Areas = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAreas()
    {
        return $this->Areas;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Areas = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAreas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Areas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Aetherytes = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAetherytes()
    {
        return $this->Aetherytes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Aetherytes = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAetherytes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Aetherytes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes RouterPaths = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRouterPaths()
    {
        return $this->RouterPaths;
    }

    /**
     * Generated from protobuf field <code>repeated bytes RouterPaths = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRouterPaths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->RouterPaths = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes GatherSpots = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGatherSpots()
    {
        return $this->GatherSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes GatherSpots = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGatherSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->GatherSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes EphemeralSpots = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEphemeralSpots()
    {
        return $this->EphemeralSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes EphemeralSpots = 11;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEphemeralSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->EphemeralSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes UnspoiledSpots = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnspoiledSpots()
    {
        return $this->UnspoiledSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes UnspoiledSpots = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnspoiledSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->UnspoiledSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes GrindSpots = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGrindSpots()
    {
        return $this->GrindSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes GrindSpots = 13;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGrindSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->GrindSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Recipes = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecipes()
    {
        return $this->Recipes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Recipes = 14;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecipes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Recipes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Npcs = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNpcs()
    {
        return $this->Npcs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Npcs = 15;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNpcs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Npcs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes FishingEntries = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFishingEntries()
    {
        return $this->FishingEntries;
    }

    /**
     * Generated from protobuf field <code>repeated bytes FishingEntries = 16;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFishingEntries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->FishingEntries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Shops = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShops()
    {
        return $this->Shops;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Shops = 17;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShops($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Shops = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Reputations = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReputations()
    {
        return $this->Reputations;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Reputations = 18;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReputations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Reputations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes GatherSkills = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGatherSkills()
    {
        return $this->GatherSkills;
    }

    /**
     * Generated from protobuf field <code>repeated bytes GatherSkills = 19;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGatherSkills($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->GatherSkills = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes FishingSpots = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFishingSpots()
    {
        return $this->FishingSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes FishingSpots = 20;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFishingSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->FishingSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Leves = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLeves()
    {
        return $this->Leves;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Leves = 21;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLeves($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Leves = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .template.TranslationMaps TranslationMaps = 22;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTranslationMaps()
    {
        return $this->TranslationMaps;
    }

    /**
     * Generated from protobuf field <code>repeated .template.TranslationMaps TranslationMaps = 22;</code>
     * @param \Template\TranslationMaps[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTranslationMaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Template\TranslationMaps::class);
        $this->TranslationMaps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Weather = 23;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWeather()
    {
        return $this->Weather;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Weather = 23;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWeather($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Weather = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes LevelingBlocks = 24;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLevelingBlocks()
    {
        return $this->LevelingBlocks;
    }

    /**
     * Generated from protobuf field <code>repeated bytes LevelingBlocks = 24;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLevelingBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->LevelingBlocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Mounts = 25;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMounts()
    {
        return $this->Mounts;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Mounts = 25;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Mounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes FishingRecords = 26;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFishingRecords()
    {
        return $this->FishingRecords;
    }

    /**
     * Generated from protobuf field <code>repeated bytes FishingRecords = 26;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFishingRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->FishingRecords = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes DiademSearchpointCircuit = 27;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDiademSearchpointCircuit()
    {
        return $this->DiademSearchpointCircuit;
    }

    /**
     * Generated from protobuf field <code>repeated bytes DiademSearchpointCircuit = 27;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDiademSearchpointCircuit($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->DiademSearchpointCircuit = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ResourceApprovals = 28;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResourceApprovals()
    {
        return $this->ResourceApprovals;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ResourceApprovals = 28;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResourceApprovals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->ResourceApprovals = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes SummoningBellIds = 29;</code>
     * @return string
     */
    public function getSummoningBellIds()
    {
        return $this->SummoningBellIds;
    }

    /**
     * Generated from protobuf field <code>bytes SummoningBellIds = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setSummoningBellIds($var)
    {
        GPBUtil::checkString($var, False);
        $this->SummoningBellIds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes RetainerNames = 30;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRetainerNames()
    {
        return $this->RetainerNames;
    }

    /**
     * Generated from protobuf field <code>repeated bytes RetainerNames = 30;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRetainerNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->RetainerNames = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes DiademSpots = 31;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDiademSpots()
    {
        return $this->DiademSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes DiademSpots = 31;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDiademSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->DiademSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Quests = 32;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQuests()
    {
        return $this->Quests;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Quests = 32;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQuests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Quests = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes CircuitSpots = 33;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCircuitSpots()
    {
        return $this->CircuitSpots;
    }

    /**
     * Generated from protobuf field <code>repeated bytes CircuitSpots = 33;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCircuitSpots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->CircuitSpots = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes SextantZoneHeaders = 34;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSextantZoneHeaders()
    {
        return $this->SextantZoneHeaders;
    }

    /**
     * Generated from protobuf field <code>repeated bytes SextantZoneHeaders = 34;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSextantZoneHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->SextantZoneHeaders = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Landpoints = 35;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLandpoints()
    {
        return $this->Landpoints;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Landpoints = 35;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLandpoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Landpoints = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Materia = 36;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMateria()
    {
        return $this->Materia;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Materia = 36;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMateria($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Materia = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Consumables = 37;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConsumables()
    {
        return $this->Consumables;
    }

    /**
     * Generated from protobuf field <code>repeated bytes Consumables = 37;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConsumables($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->Consumables = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ItemSeries = 38;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemSeries()
    {
        return $this->ItemSeries;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ItemSeries = 38;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemSeries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->ItemSeries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes DiademMobs = 39;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDiademMobs()
    {
        return $this->DiademMobs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes DiademMobs = 39;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDiademMobs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->DiademMobs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes TreasureMaps = 40;</code>
     * @return string
     */
    public function getTreasureMaps()
    {
        return $this->TreasureMaps;
    }

    /**
     * Generated from protobuf field <code>bytes TreasureMaps = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setTreasureMaps($var)
    {
        GPBUtil::checkString($var, False);
        $this->TreasureMaps = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes IshgardPoints = 41;</code>
     * @return string
     */
    public function getIshgardPoints()
    {
        return $this->IshgardPoints;
    }

    /**
     * Generated from protobuf field <code>bytes IshgardPoints = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setIshgardPoints($var)
    {
        GPBUtil::checkString($var, False);
        $this->IshgardPoints = $var;

        return $this;
    }

}

