<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace Template;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>template.TranslationMaps</code>
 */
class TranslationMaps extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.template.Language Language = 1;</code>
     */
    protected $Language = 0;
    /**
     * Generated from protobuf field <code>map<string, string> KeyToName = 2;</code>
     */
    private $KeyToName;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Language
     *     @type array|\Google\Protobuf\Internal\MapField $KeyToName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.template.Language Language = 1;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->Language;
    }

    /**
     * Generated from protobuf field <code>.template.Language Language = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \Template\Language::class);
        $this->Language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> KeyToName = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getKeyToName()
    {
        return $this->KeyToName;
    }

    /**
     * Generated from protobuf field <code>map<string, string> KeyToName = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setKeyToName($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->KeyToName = $arr;

        return $this;
    }

}

